src/3d/fields/fields.f90
src/3d/inversion/inversion.f90
unit-tests/3d/test_velgradg.f90
unit-tests/3d/test_vtend.f90

This pull request reduces the amount of memory used for an EPIC simulation. Instead of 9 elements of the velocity gradient tensor per grid point, only 5 elements are stored. It makes use of the assumption of incompressibility and the relation between vorticity and spatial velocity derivatives.

3D vorticity tendency less memory

---

src/parcels/parcel_container.f90

@sjboeing I fix this now also in the main branch. It is already fixed in the develop branch (see #279), but this is not yet merged with the main branch.

Fix get_delx for non-centred domains

---

src/parcels/parcel_correction.f90
src/parcels/parcel_init.f90
src/parcels/parcel_interpl.f90

We currently use the name `trilinear` in 2D, but it should be named `bilinear` instead.

Use proper interpolation name

---

analyse/genspec.f90
src/2d/parcels/parcel_init.f90

For large problem sizes OpenMP has issues, that is, one gets a segmentation fault since it cannot handle the size on stack. We need to use heap memory.

Use heap memory

---

Makefile.am
README.md
configure.ac
python-scripts/Makefile.am
run-script/Makefile.am

Replace `--disable-python-check` with `--enable-python`. The current version causes an error when doing `make install` and Python is not available.

Enable Python

---

src/2d/epic2d.f90
src/2d/parcels/parcel_init.f90
src/2d/parcels/parcel_merge.f90
src/2d/parcels/parcel_nearest.f90
src/2d/parcels/parcel_netcdf.f90
src/2d/utils/options.f90
src/2d/utils/parameters.f90
src/3d/epic3d.f90
src/3d/parcels/parcel_container.f90
src/3d/parcels/parcel_ellipsoid.f90
src/3d/parcels/parcel_init.f90
src/3d/parcels/parcel_merge.f90
src/3d/parcels/parcel_nearest.f90
src/3d/parcels/parcel_netcdf.f90
src/3d/utils/options.f90
src/3d/utils/parameters.f90
src/utils/constants.f90

We currently set the maximum number of parcels as a constant `max_num_parcels`. This causes issues when increasing the grid resolution. We should make this a runtime dependent value. I suggest to use `max_num_parcels = nx * ny * nz * n_per_cell * size_factor` (and `nx * nz * n_per_cell * size_factor` in 2D) where `size_factor` is a user-defined input parameter.

Dynamic maximum number of parcels

---

src/utils/jacobi.f90
unit-tests/3d/Makefile.am
unit-tests/3d/test_jacobi_4.f90
unit-tests/netcdf/test_netcdf_dataset_2d.f90

The Jacobi solver fails for matrices with zeros on the diagonal.

Fix Jacobi solver

---

src/utils/jacobi.f90

We need to add epsilon with the correct sign, we can get division by zero otherwise.

Add with correct sign

---

src/utils/jacobi.f90

In the current version of the 3D paper we write the Jacobi convergence criterion is when the absolute sum of the off-diagonals `sm` is less than `atol`. We need to make the exit statement of the `while` loop to be `sm >= atol` to be consistent.

Change to criterion used in paper

---

unit-tests/netcdf/test_mpi_netcdf_dataset_1d.f90
unit-tests/netcdf/test_mpi_netcdf_dataset_2d.f90
unit-tests/netcdf/test_mpi_netcdf_dataset_3d.f90
unit-tests/netcdf/test_mpi_netcdf_read_attributes.f90
unit-tests/netcdf/test_mpi_netcdf_read_dataset_1d.f90
unit-tests/netcdf/test_mpi_netcdf_read_dataset_2d.f90
unit-tests/netcdf/test_mpi_netcdf_read_dataset_3d.f90

We must use `MPI_LAND` and not `MPI_LOR` to check for errors.

Fix MPI reduction

---

src/3d/epic3d.f90
src/3d/fields/field_netcdf.f90
src/3d/inversion/inversion.f90
src/3d/inversion/inversion_utils.f90
src/3d/parcels/parcel_correction.f90
src/3d/parcels/parcel_diagnostics.f90
src/3d/parcels/parcel_interpl.f90
src/3d/stepper/ls_rk4.f90
src/3d/utils/utils.f90
src/utils/physics.f90
src/utils/timer.f90
unit-tests/3d/Makefile.am
unit-tests/3d/test_gradient_correction_3d.f90
unit-tests/3d/test_laplace_correction_3d.f90
unit-tests/3d/test_parcel_correction_3d.f90
unit-tests/3d/test_vor2vel.f90
unit-tests/3d/test_vtend.f90

This PR
* changes to the new inversion method
* corrects the parcel tendency after each RK4 step to prevent a growth of the net vorticity
* changes to flux form in the vorticity tendency calculation
* introduces symmetry BC for vorticity
* adds writing the gridded volume to file

Flux form including new inversion and net vorticity correction

---

src/3d/inversion/inversion.f90
src/3d/inversion/inversion_utils.f90
src/3d/parcels/parcel_interpl.f90
unit-tests/3d/Makefile.am
unit-tests/3d/test_diffz2.f90
unit-tests/3d/test_diffz3.f90
unit-tests/3d/test_diffz4.f90
unit-tests/3d/test_diffz5.f90

This PR
- use FD for performing vertical derivatives
- fixes the subroutine diffz
- adds more unit tests for diffz and central_diffz

Use central differencing in solenoidal correction and tendency calculation

---

src/3d/inversion/inversion.f90
unit-tests/2d/test_gradient_correction.f90
unit-tests/2d/test_laplace_correction.f90
unit-tests/2d/test_parcel_correction.f90
unit-tests/3d/test_gradient_correction_3d.f90
unit-tests/3d/test_laplace_correction_3d.f90
unit-tests/3d/test_parcel_correction_3d.f90
unit-tests/unit_test.f90

This pull request
* fixes the verbose mode in the parcel correction unit tests
* fixes a comment in inversion.f90
* updates the initialisation of the parcels in the 3D parcel correction unit tests

Fix verbose mode and update initialisation in parcel correction unit tests

---

src/3d/epic3d.f90
src/3d/fields/field_netcdf.f90
src/3d/parcels/parcel_init.f90
src/3d/utils/utils.f90
unit-tests/3d/test_parcel_init_3d.f90

We currently use a special algorithm (explained in https://doi.org/10.1016/j.jcpx.2022.100109) to ensure that par2grid yields the initial gridded data. However, this causes over/under shoots of parcel attributes near the boundaries. We now switch to a simpler parcel initialisation that avoids this issue.

Initialise parcels like grid2par

---

src/3d/parcels/parcel_diagnostics.f90
src/3d/parcels/parcel_diagnostics_netcdf.f90
src/3d/utils/utils.f90
unit-tests/3d/test_mpi_parcel_diagnostics.f90

We remove the peref calculation for 3D as the result is too inaccurate and the calculation involves a global sort across all MPI ranks which we do not want to do.
Closes #370.

Remove reference potential energy calculation for 3D

---

src/3d/epic3d.f90
src/3d/parcels/parcel_container.f90
src/3d/parcels/parcel_diagnostics.f90
src/3d/parcels/parcel_interpl.f90
src/3d/parcels/parcel_nearest.f90
src/3d/stepper/ls_rk4.f90
src/3d/utils/utils.f90
unit-tests/3d/test_mpi_grid2par.f90
unit-tests/3d/test_mpi_parcel_diagnostics.f90

We need to communicate the RK4 variables along with the parcel attributes. It is best to make them part of the parcel container and use the existing parcel halo swap routine.

Make RK4 variables part of the parcel container

---

src/3d/Makefile.am
src/3d/epic3d.f90
src/3d/fields/field_mpi.f90
src/3d/fields/fields.f90
src/3d/parcels/parcel_container.f90
src/fft/sta3dfft.f90
src/mpi/mpi_reverse.f90

We have not de-allocated some arrays properly.

Proper de-allocation of allocatable arrays

---

src/netcdf/netcdf_writer.f90

The signature of `write_netcdf_axis_3d` takes two optional parameters. If they are not specified, we get a segmentation fault.
>Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
>Backtrace for this error:
>0  0x7f862565ad21 in ???
>1  0x7f8625659ef5 in ???
>2  0x7f86252b208f in ???
>	at /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
>3  0x7f8625b9f448 in __netcdf_writer_MOD_write_netcdf_axis_3d
>	at ../../../src/netcdf/netcdf_writer.f90:413
>4  0x411ab8 in generate_fields
>	at ../../../models/3d/epic3d-models.f90:91
>5  0x40f36b in epic3d_models
>	at ../../../models/3d/epic3d-models.f90:39
>6  0x411bca in main
>	at ../../../models/3d/epic3d-models.f90:5
>Segmentation fault (core dumped)

Fix write_netcdf_axis_3d

---

src/3d/inversion/inversion_utils.f90
unit-tests/3d/test_mpi_gradient_correction_3d.f90
unit-tests/3d/test_mpi_laplace_correction_3d.f90
unit-tests/3d/test_mpi_nearest_1.f90
unit-tests/3d/test_mpi_nearest_10.f90
unit-tests/3d/test_mpi_nearest_11.f90
unit-tests/3d/test_mpi_nearest_12.f90
unit-tests/3d/test_mpi_nearest_13.f90
unit-tests/3d/test_mpi_nearest_14.f90
unit-tests/3d/test_mpi_nearest_15.f90
unit-tests/3d/test_mpi_nearest_16.f90
unit-tests/3d/test_mpi_nearest_17.f90
unit-tests/3d/test_mpi_nearest_18.f90
unit-tests/3d/test_mpi_nearest_19.f90
unit-tests/3d/test_mpi_nearest_2.f90
unit-tests/3d/test_mpi_nearest_20.f90
unit-tests/3d/test_mpi_nearest_3.f90
unit-tests/3d/test_mpi_nearest_4.f90
unit-tests/3d/test_mpi_nearest_5.f90
unit-tests/3d/test_mpi_nearest_6.f90
unit-tests/3d/test_mpi_nearest_7.f90
unit-tests/3d/test_mpi_nearest_8.f90
unit-tests/3d/test_mpi_nearest_9.f90
unit-tests/3d/test_mpi_reverse_x.f90
unit-tests/3d/test_mpi_reverse_y.f90
unit-tests/3d/test_mpi_vel2vgrad.f90

This PR
* fixes some unit tests after changing the initialisation interface of `mpi_reverse.f90` and `parcel_nearest.f90`.
* fixes the `Floating-point exception - erroneous arithmetic operation` error happening in `set_hyperbolic_functions` of `inversion_utils.f90` due to underflow. This fix is only applied in debug mode.
* slightly misaligns the position of `x` or `y` in `test_mpi_nearest_3.f90` and `test_mpi_nearest_4.f90` as round-off errors cause the parcels to be assigned to different grid points that then results in `Merge error: no near neighbour found`.
* fixes `n_total_parcels` in `test_mpi_gradient_correction_3d.f90`.

Fix MPI unit tests

---

analyse/2d/genspec2d.f90
analyse/3d/genspec3d.f90
configure.ac
src/2d/stepper/rk4_utils.f90
src/2d/utils/utils.f90
src/3d/stepper/rk4_utils.f90
src/3d/utils/utils.f90

When compiling with `-Wuninitialized -Wmaybe-uninitialized` we get warnings of "maybe uninitialised" variables. The reason are  `allocatable` characters. We get rid of them by specifying a size.

No allocatable strings

---

src/3d/parcels/parcel_container.f90
src/3d/parcels/parcel_ellipsoid.f90

We must communicate Veta and Vtau as well. Another solution: We do not reuse them, but calculate them all the time in `vol2grid`, `par2grid` and the parcel corrections. We must communicate them due to the parcel halo swap calls.

Communicate veta and vtau

---

src/utils/scherzinger.f90
unit-tests/3d/test_ellipsoid_reflection.f90

This PR applies the bug fixes for the Scherzinger eigenvalue/-vector solver (see #500) to the parallel version.

Fixes from serial version

---

src/3d/inversion/inversion.f90

This small fix to the inversion (indices start with zero instead of 1) seems to solve some of the issues with reproducibility in parallel.

Fixes issue with zero-indexing in inversion module

---

src/3d/inversion/inversion.f90
src/3d/inversion/inversion_utils.f90

Fortran creates temporary arrays when passing sub-ranges to subroutines.

Avoid array temporaries

---

mpi-tests/test_merging_parcels.f90
mpi-tests/test_parcel_merge_random.f90
mpi-tests/test_parcel_split_merge.f90
mpi-tests/test_utils.f90
src/3d/epic3d.f90
src/3d/parcels/parcel_diagnostics.f90
src/3d/parcels/parcel_diagnostics_netcdf.f90
src/3d/parcels/parcel_merge.f90

Remove subroutine input argument. We do not need to pass the parcel container.

Simplify parcel merge routine call

---

unit-tests/3d/test_mpi_diffz2.f90
unit-tests/3d/test_mpi_diffz3.f90
unit-tests/3d/test_mpi_diffz4.f90
unit-tests/3d/test_mpi_diffz5.f90
unit-tests/3d/test_mpi_gradient_correction_3d.f90
unit-tests/3d/test_mpi_laplace_correction_3d.f90
unit-tests/3d/test_mpi_parcel_correction_3d.f90
unit-tests/3d/test_mpi_parcel_init_3d.f90
unit-tests/3d/test_mpi_trilinear.f90

This PR
* registers the missing `halo_swap_timer` in some unit-tests.
* changes the function call as we now distinguish between spectral and physical space vertical derivatives (see #504).

Fix unit-tests -- register missing timer and fix function call

---

configure.ac

This PR
* removes the `-fPIC` (position-independent code) compile flag
* increments the version from 0.13.0 to 0.13.1 in `configure.ac`

Remove -fPIC flag

---

src/3d/parcels/parcel_mpi.f90

The parcel communication buffers do not include the vertical halo cells. We must increase their size.

Increase buffer in parcel communication

---

src/3d/fields/field_diagnostics_netcdf.f90
src/3d/inversion/inversion_utils.f90

Only the root rank writes the field statistics. All other MPI ranks leave early, hence they must stop their timers.

Add missing field statistics timer stop

---

src/3d/utils/utils.f90
src/utils/physics.f90

We currently do not calculate the (squared) buoyancy frequency in restart mode. This PR changes to the buoyancy frequency (as input) and calculates only if not provided.

Calculate squared buoyancy frequency only if not provided

---

.zenodo.json

We use the old format for the `.zenodo.json`.

Fix .zenodo.json

---

src/3d/parcels/parcel_diagnostics.f90
src/3d/parcels/parcel_diagnostics_netcdf.f90
src/3d/parcels/parcel_merge.f90

Write parcel merger statistics to the netCDF file.

Collect merger statistics

---

examples/moist.config
src/3d/Makefile.am
src/3d/epic3d.f90
src/3d/fields/fields.f90
src/3d/parcels/parcel_damping.f90
src/3d/parcels/parcel_interpl.f90
src/3d/stepper/ls_rk.f90
src/3d/stepper/rk_utils.f90
src/3d/utils/options.f90

Damping implementation

---

src/3d/parcels/parcel_diagnostics_netcdf.f90

This PR fixes two things:
1. the timer was not stopped for MPI ranks != root rank
2. the parcel split and merge counters were not reset for ranks != root rank

Add missing stop_timer; fix resetting parcel split and merge diagnostics

---

src/3d/fields/fields.f90
src/3d/inversion/inversion.f90
src/3d/parcels/parcel_container.f90
src/3d/parcels/parcel_interpl.f90
src/3d/stepper/ls_rk.f90
src/3d/stepper/rk_utils.f90
unit-tests/3d/test_mpi_parcel_read.f90
unit-tests/3d/test_mpi_parcel_read_rejection.f90
unit-tests/3d/test_mpi_parcel_write.f90
unit-tests/3d/test_mpi_vel2vgrad.f90

This branch uses only gridded strain field to deform parcels. Changes to save B33 and use matrix exponentiation not yet included.

Gridded strain

---

mpi-tests/benchmark_parcel_merging.f90
src/3d/parcels/parcel_netcdf.f90
src/netcdf/netcdf_reader.f90

This PR adds an optimised rejection method for reading a parcel dataset. If the dataset contains the MPI decomposition boxes and start indices, they will be used to selectively read parcels, i.e. not all MPI ranks read all parcels. This increases the performance for restarts from parcel files using different number of MPI ranks as the written restart file.

Add optimised rejection method

---

configure.ac
src/3d/parcels/parcel_container.f90
src/3d/parcels/parcel_init.f90
src/3d/parcels/parcel_merge.f90
src/3d/parcels/parcel_netcdf.f90
src/3d/parcels/parcel_split.f90
src/netcdf/netcdf_reader.f90
src/netcdf/netcdf_writer.f90
src/utils/armanip.f90

Hi @matt-frey. Here is the branch that adds labels for the workshop. It is disabled by default. We may still change the dilution at some point to deal with parcels with the same labels merging, but this is not as trivial as I thought. The other thing to consider is to reset the labels every time diagnostics are created. If we do this, we can create animations of parcel trajectories (won't have time to do this before the workshop, it also means tracking over longer time scales becomes more involved).

Add labels to code

---

src/3d/parcels/parcel_netcdf.f90

This branch resets the labels and dilution every time we write to NetCDF. Using an iterative approach, we can now map between 2 arbitrary times.

Reset labels and dilution when writing to netCDF

---

mpi-tests/benchmark_parcel_merging.f90
src/3d/parcels/parcel_container.f90
src/3d/parcels/parcel_netcdf.f90

We must set the total number of parcels before calling `parcel_communicate` as otherwise it fails in debug mode due to checks.

Set total number of parcels before parcel_communicate

---

src/3d/parcels/parcel_netcdf.f90

With https://github.com/EPIC-model/epic/commit/faa89ffa41515cb910d5e16b59e6c6e771c48c58#diff-aa80479ec21430b1df16920459f5125ea4b52bdc7c0f3c2e9bec2b9e13fe2e5dR478 we added a line to set / increment the number of parcels `n_parcels` which is used for the optimised rejection method (when `xlo`, `xhi`, `ylo` and `yhi` are present. However, this breaks the inefficient rejection method which already sets / updateds the number of parcels (here: https://github.com/EPIC-model/epic/pull/570/files#diff-aa80479ec21430b1df16920459f5125ea4b52bdc7c0f3c2e9bec2b9e13fe2e5dL466).

Fix rejection method

---

mpi-tests/verify_parcel_merging.f90

When we compare the serial and parallel version of the nearest algorithm, the serial version writes the parcel file. Therefore, the domain specified by `xlo`, `xhi`, `ylo` and `yhi` covers the whole domain. In order to read the parcels with the inefficient rejection method, the serial should not write these bounds. To do this, we explicitly specify which attributes to write.

Explicitly set the attributes to write

---

src/3d/parcels/parcel_container.f90
src/3d/parcels/parcel_netcdf.f90

Resets the labels on restarts, and fixes a wrong ifdef.

Bugfixes to labelling

---

mpi-tests/test_parcel_merge_random.f90
mpi-tests/test_parcel_split_random.f90
mpi-tests/test_utils.f90

This PR fixes the following problems in the MPI tests:
* a single parcel could be increased multiple times causing support points to be outside the domain (`par2grid`)
* some timers were not initialised

Fix MPI tests

---

src/3d/fields/field_diagnostics_netcdf.f90
src/3d/fields/field_netcdf.f90
src/3d/parcels/parcel_diagnostics_netcdf.f90
src/3d/parcels/parcel_netcdf.f90
src/netcdf/netcdf_utils.f90

We are facing the issue of character string initialisation with (presumably) some compilers. The problem arises in the initialisation of the `netcdf_info` type. The assignment of character strings of shorter length than the actual type causes issues; e.g. a name like `x_velocity` suddently reads `x_volocity`. An explicit setter function fixes the issue.

Explicit setter for type netcdf_info

---

configure.ac

The AC_LANG_PROGRAM check for netcdf-c is wrong. The header must be added as the first argument. See also https://www.gnu.org/software/autoconf/manual/autoconf-2.61/html_node/Generating-Sources.html.

Fix AC_LANG_PROGRAM for netcdf-c

---

src/mpi/mpi_layout.f90

The variable `last` is passed with `intent(out)`. We cannot use the variable before it is assigned. Also, this lines has no effect because a value is assigned to the variable at the end of the routine.

Fix error in get_local_bounds

---

src/utils/physics.f90

There is a label mismatch for the panetary vorticity input, which results in ignoring the flag at restarts.

Fix label of planetary vorticity

---

src/3d/parcels/parcel_netcdf.f90

When we write parcel files and then restart a simulation, we must ensure the MPI decomposition is identical. Otherwise, this leads to an incorrect reading of parcel data.

Fix issue when MPI ranks agree but MPI decomposition is different
