src/3d/parcels/parcel_diagnostics.f90, src/3d/parcels/parcel_ellipsoid.f90, src/3d/parcels/parcel_split.f90, src/3d/stepper/rk4_utils.f90, src/utils/jacobi.f90, unit-tests/3d/test_jacobi_1.f90, unit-tests/3d/test_jacobi_2.f90, unit-tests/3d/test_jacobi_3.f90
This pull request improves the Jacobi eigenvalue solver.
=> Improve Jacobi

h5_to_nc.py, src/2d/utils/phys_parameters.f90, src/3d/utils/phys_parameters.f90
Changing the naming of L_c to L_v, and adding a python script to convert to netcdf
=> Sboeing dec 2021

src/2d/epic2d.f90, src/2d/fields/field_diagnostics.f90, src/2d/fields/field_hdf5.f90, src/2d/parcels/parcel_diagnostics.f90, src/2d/parcels/parcel_hdf5.f90, src/2d/parcels/parcel_init.f90, src/2d/utils/options.f90, src/2d/utils/utils.f90, src/3d/epic3d.f90, src/3d/fields/field_diagnostics.f90, src/3d/fields/field_hdf5.f90, src/3d/parcels/parcel_diagnostics.f90, src/3d/parcels/parcel_hdf5.f90, src/3d/parcels/parcel_init.f90, src/3d/utils/options.f90, src/3d/utils/utils.f90, src/hdf5/h5_reader.f90, src/hdf5/h5_utils.f90, src/hdf5/h5_writer.f90
Add the feature of restarting EPIC using either a field file or parcel file.
=> Restarting EPIC

src/2d/parcels/parcel_container.f90, src/3d/parcels/parcel_container.f90
=> Fix calculation of get_delx and get_dely for non-centred domains

src/2d/epic2d.f90, src/2d/utils/options.f90
This change must be merged into `develop` and `main.
=> Add initial time like in the 3D model

src/2d/parcels/parcel_container.f90, src/2d/parcels/parcel_merge.f90
The fix merged with #297 must also be applied to the master branch.
=> Apply pull request #297 to master branch

licenses/python/NUMBA_LICENSE, python-scripts/subgrid_2d_generalised.py, python-scripts/tools/bokeh_plots.py, python-scripts/tools/h5_reader.py, python-scripts/tools/mpl_beautify.py, python-scripts/tools/mpl_style.py, python-scripts/tools/plots.py, python-scripts/tools/units.py, requirements.txt
This pull request:
* speeds up the plotting of the parcels
* updates requirements.txt
* adds the Numba package license
* uses `get_label` more consistently
* updates the matplotlib LaTeX preamble to include the siunitx package
* extends the SGS script to write multiple steps
=> Improve Python scripts

licenses/python/COLORCET_LICENSE, python-scripts/tools/h5_reader.py, python-scripts/tools/plots.py
This PR
* adds the license of the Python colorcet package
* fixes some calls to `get_dataset`.
=> Fix access of datasets + add colorcet license

src/2d/fields/field_diagnostics_netcdf.f90, src/2d/parcels/parcel_diagnostics_netcdf.f90, src/2d/parcels/parcel_netcdf.f90, src/3d/fields/field_diagnostics_netcdf.f90, src/3d/parcels/parcel_diagnostics_netcdf.f90, src/netcdf/netcdf_writer.f90, src/utils/physics.f90
There are some unused variables and typos.
=> Fix compilation in debug mode

src/3d/stepper/rk4_utils.f90
We must take the largest eigenvalue in magnitude. Eigenvalues can be negative!
=> Fix time step estimate

src/3d/fields/field_diagnostics.f90, src/3d/fields/field_diagnostics_netcdf.f90, src/3d/parcels/parcel_diagnostics.f90, src/3d/parcels/parcel_diagnostics_netcdf.f90, src/mpi/mpi_collectives.f90, src/mpi/mpi_layout.f90, src/netcdf/netcdf_utils.f90, unit-tests/3d/Makefile.am, unit-tests/3d/test_mpi_field_diagnostics.f90, unit-tests/3d/test_mpi_parcel_diagnostics.f90, unit-tests/mpi/test_mpi_layout.f90
This pull request implements the parcel and field diagnostics with MPI. However, the reference potential energy is not correct (see also #370). This should be fixed in another pull request.
=> Parcel and field diagnostics in parallel

src/3d/fields/field_diagnostics_netcdf.f90, src/3d/fields/field_netcdf.f90, src/3d/parcels/parcel_init.f90
This PR can be finished/pulled once #361 is pulled in.
=> Read and write fields in parallel

src/3d/parcels/parcel_container.f90, src/3d/parcels/parcel_diagnostics.f90, src/3d/parcels/parcel_netcdf.f90, src/netcdf/netcdf_reader.f90, unit-tests/3d/Makefile.am, unit-tests/3d/test_mpi_parcel_read.f90, unit-tests/3d/test_mpi_parcel_write.f90
We currently only support reading parcels if the start index dataset is part of the provided NetCDF parcel file. See also #371.
=> Read and write parcels in parallel

src/3d/fields/fields.f90, src/3d/parcels/parcel_container.f90, src/3d/parcels/parcel_ellipsoid.f90, src/3d/parcels/parcel_netcdf.f90, src/mpi/mpi_layout.f90, unit-tests/3d/Makefile.am, unit-tests/3d/test_mpi_parcel_read_rejection.f90
=> Parcel rejection method

unit-tests/3d/Makefile.am, unit-tests/3d/test_fft_3d_sphere.f90
Hi both,
Here is some work on setting up the addiotional FFT unit test.
Cheers,
Steef
=> Additional FFT unit test

src/3d/epic3d.f90, src/3d/fields/fields.f90, src/3d/inversion/inversion.f90, src/3d/inversion/inversion_utils.f90, src/3d/parcels/parcel_correction.f90, src/3d/stepper/ls_rk4.f90, src/3d/utils/utils.f90
This PR pulls the newly developed inversion method into EPIC.
=> Porting new inversion to EPIC

src/2d/stepper/ls_rk4.f90, src/3d/stepper/ls_rk4.f90
=> Rename RK4 constants

src/2d/parcels/parcel_container.f90, src/2d/parcels/parcel_nearest.f90, src/2d/utils/parameters.f90
This does the same fix in 2D as in 3D. However, we did not experience any issues in 2D.
=> Apply nearest fix in 2d

python-scripts/tools/animate/bokeh_animation.py, python-scripts/tools/bokeh_plots.py, python-scripts/tools/nc_reader.py, python-scripts/tools/units.py
=> Fix python scripts due to NetCDF interface

examples/moist.config, examples/moist.nml, examples/write_moist_setup.py, models/3d/moist_3d.f90, src/utils/constants.f90
@matt-frey: replacing the moist setup with a smooth bubble. Limiting to 1000 seconds.
=> Changes to moist setup: shorter run, smooth edge bubble

examples/write_moist_setup.py, python-scripts/tools/nc_fields.py, python-scripts/tools/nc_parcels.py, src/3d/utils/parameters.f90
=> Restarts with zeta flags

src/3d/epic3d.f90, src/3d/fields/field_diagnostics.f90, src/3d/fields/field_diagnostics_netcdf.f90, src/3d/inversion/inversion.f90, src/3d/parcels/parcel_diagnostics.f90, src/3d/parcels/parcel_diagnostics_netcdf.f90
This PR
* adds minimum and maximum buoyancy evaluation for fields and parcels
* adds enstrophy calculation on the grid
* removes some deprecated code and comments
* renames `psi` to `en` for consistency
=> Add more statistics

src/3d/parcels/parcel_interpl.f90
The two lines setting zeta to zero were not removed.
=> Fix parcel interpolation

src/2d/epic2d.f90, src/2d/parcels/parcel_diagnostics.f90, src/2d/utils/utils.f90, src/3d/epic3d.f90, src/3d/parcels/parcel_diagnostics.f90, src/3d/parcels/parcel_diagnostics_netcdf.f90, src/3d/utils/utils.f90, src/utils/physics.f90
=> Peref in NetCDF output

src/2d/epic2d.f90, src/3d/epic3d.f90, src/netcdf/netcdf_utils.f90
=> Check if file exists

models/2d/epic2d-models.f90, src/2d/fields/field_diagnostics.f90, src/2d/fields/field_diagnostics_netcdf.f90, src/2d/parcels/parcel_diagnostics.f90, src/2d/parcels/parcel_diagnostics_netcdf.f90, src/2d/utils/parameters.f90, src/3d/fields/field_diagnostics.f90, src/3d/fields/field_diagnostics_netcdf.f90, src/3d/parcels/parcel_diagnostics.f90, src/3d/parcels/parcel_diagnostics_netcdf.f90, src/3d/utils/parameters.f90, src/utils/physics.f90, unit-tests/2d/test_ellipse_split.f90
In the PS3D paper we calculated the domain-averaged kinetic energy and enstrophy. I suggest we directly calculate the domain-averaged quantities in EPIC.
=> Domain averaged quantities in 2D and 3D and protected parameters in 2D

src/3d/utils/options.f90
Just spotted this little thing
=> Setting 3D default n per cell to 8 (a cube)

src/3d/parcels/parcel_mpi.f90, src/3d/parcels/parcel_nearest.f90, src/mpi/mpi_layout.f90, unit-tests/3d/test_mpi_nearest_1.f90
Move from active to passive target communication. See also https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node279.htm for reference about the terminology.
=> MPI passive communication in nearest algorithm

configure.ac
Improve library search during the configuration step.
=> Improve the search for libraries

examples/moist.config, examples/robert.config, examples/robert3d.config, examples/straka.config, examples/taylor_green.config, src/3d/inversion/inversion.f90, src/3d/parcels/parcel_init.f90, src/3d/parcels/parcel_interpl.f90, src/3d/stepper/rk4_utils.f90
Some bugfixes related to halo swapping and config files.
=> Changes on halo swapping branch

examples/moist.config, examples/robert.config, examples/robert3d.config, examples/straka.config, examples/taylor_green.config, src/3d/epic3d.f90, src/3d/fields/field_diagnostics_netcdf.f90, src/3d/inversion/inversion.f90, src/3d/parcels/parcel_bc.f90, src/3d/parcels/parcel_diagnostics_netcdf.f90, src/3d/parcels/parcel_init.f90, src/3d/parcels/parcel_interpl.f90, src/3d/parcels/parcel_merge.f90, src/3d/parcels/parcel_netcdf.f90, src/3d/parcels/parcel_split.f90, src/3d/stepper/ls_rk4.f90, src/3d/stepper/rk4_utils.f90, src/3d/utils/utils.f90, src/netcdf/netcdf_utils.f90, src/netcdf/netcdf_writer.f90
This PR
- adds missing parcel halo swap calls
- adds parallelism to the time step calculation
- adds missing field halo fill calls
- adds missing updates of the total number of parcels
Close #454.
=> Fix MPI related issues

src/3d/parcels/parcel_nearest.f90
This PR
* removes print statements used for debugging
* adds an additional check in debug mode
=> Cleanup and additional debug check in parcel nearest

src/3d/parcels/parcel_correction.f90
Applies #484 to the parallel version.
=> Fix the vorticity correction

examples/beltrami.config, examples/moist.config, examples/robert3d.config, mpi-tests/test_utils.f90, src/3d/Makefile.am, src/3d/epic3d.f90, src/3d/stepper/ls_rk.f90, src/3d/stepper/rk_utils.f90, src/3d/utils/options.f90, src/3d/utils/utils.f90
This PR adds the 3rd order RK stepper. Users can select between 3rd and 4th order RK.
=> 3rd order RK stepper

mpi-tests/test_parcel_split_merge.f90, mpi-tests/test_parcel_split_random.f90, mpi-tests/test_utils.f90, src/3d/epic3d.f90, src/3d/parcels/parcel_container.f90, src/3d/parcels/parcel_ellipsoid.f90, src/3d/parcels/parcel_init.f90, src/3d/parcels/parcel_mpi.f90, src/3d/parcels/parcel_split.f90, src/3d/utils/options.f90, src/3d/utils/parameters.f90, src/utils/Makefile.am, src/utils/armanip.f90, unit-tests/3d/test_ellipsoid_split.f90, unit-tests/3d/test_mpi_parcel_split.f90
This PR
* adds two new input options (`parcel%grow_factor` and `parcel%shrink_factor`) to adjust the parcel container.
* fixes the first estimate of `max_num_parcels` to include the number of halo cells too.
Closes #491.
=> Resize parcel container

src/3d/parcels/parcel_nearest.f90
According to https://enccs.github.io/intermediate-mpi/one-sided-sync/#passive-target-communication (accessed 12 June 2023) it is safer to use MPI_Win_allocate for passive target communication.
=> Use MPI_Win_allocate instead of MPI_Win_create

mpi-tests/test_parcel_split_merge.f90, mpi-tests/test_parcel_split_random.f90, src/3d/Makefile.am, src/3d/fields/fields.f90, src/3d/parcels/parcel_bc.f90, src/3d/parcels/parcel_correction.f90, src/3d/parcels/parcel_interpl.f90, src/3d/parcels/parcel_merge.f90, src/3d/parcels/parcel_mpi.f90, src/3d/parcels/parcel_nearest.f90, src/3d/parcels/parcel_split.f90, src/3d/stepper/ls_rk.f90, src/mpi/mpi_layout.f90
Round-off errors cause issues with parcels on periodic edges.
=> Fix parcels on periodic edge

src/3d/inversion/inversion_utils.f90, src/3d/parcels/parcel_diagnostics.f90, src/mpi/mpi_environment.f90
=> Fix OpenMP race condition in inversion_utils.f90

CHANGELOG.md
This PR
* adds merged PRs
* change end of line to unix format.
=> Update changelog version 0.13.0

src/3d/epic3d.f90, src/3d/fields/field_netcdf.f90, src/3d/parcels/parcel_container.f90, src/3d/parcels/parcel_merge.f90, src/3d/parcels/parcel_split.f90, src/3d/utils/options.f90, src/3d/utils/utils.f90
This PR
* changes the writing of fields: Fields can be enabled and disabled.
* reduces the amount of information printed in verbose mode
=> Write specific fields only

src/3d/fields/field_diagnostics.f90, src/3d/fields/field_mpi.f90, src/3d/parcels/parcel_interpl.f90, src/3d/utils/parameters.f90
This PR
* fixes nparg and nsparg
* changes amax
=> Do halo swap for nparg and nsparg

src/3d/parcels/parcel_interpl.f90
PR #523 slightly messed up the opening and closing of OpenMP regions in `par2grid`.
=> Fix OpenMP pragmas

src/3d/utils/utils.f90
This PR changes / fixes the frequency of writes.
=> Fix the write frequency

.zenodo.json
Add the ORCID and fix the names in the metadata. See also
* https://developers.zenodo.org/#update-schedule
* https://developers.zenodo.org/#representation
=> Overwrite default Zenodo metadata

src/3d/fields/field_diagnostics.f90
This bug only affects writing the field statistics when then buoyancy perturbation mode is enabled.
=> Need to calculate buoyancy extrema for total buoyancy

src/3d/parcels/parcel_nearest.f90
Only check local parcels after globally closest parcel determined.
=>  Fix loop for nearest parcel check

src/3d/parcels/parcel_damping.f90, src/3d/utils/options.f90
Hi Matthias,
Here is a PR which adds damping that is specific to the surface and top layer, as well as making the damping more consistent for moist and dry cases.
=> Implement generalised damping, including surface damping

docs/html/intro.html
=> Upload recompiled manual

docs/manual/installation.adoc
=> Fix Python version in Python environment setup

src/2d/fields/fields.f90, src/3d/parcels/parcel_netcdf.f90
Just fixing a few small bugs detected while working on matrix exp time integration.
=> Fixes detected in debugging (symmetry checks/labels)
